USE pandemic;

DROP FUNCTION IF EXISTS YEARS_FROM_CURRENT;
DELIMITER //;

CREATE FUNCTION YEARS_FROM_CURRENT(year INT)
    RETURNS INT
    NO SQL DETERMINISTIC
BEGIN
    DECLARE year_start_date DATE DEFAULT MAKEDATE(year, 1);
    DECLARE today DATE DEFAULT CURDATE();
    RETURN TIMESTAMPDIFF(YEAR, year_start_date, today);
END;

DELIMITER ;

SELECT id,
       year,
       YEARS_FROM_CURRENT(year) AS 'diff_years'
FROM cases;
